### ISSUE TITLE
Is it possible to use it as an HTTPs Proxy?

### ISSUE THREAD

**Issue by gcavalcante8808** [awslabs/aws-sigv4-proxy#59]
Hi Folks,

I'm evaluating the aws-sigv4-proxy to access some opensearch instances and for that I made the following setup:

docker-compose.yaml
```yaml
version: '3'

services:
  proxy:
    image: public.ecr.aws/aws-observability/aws-sigv4-proxy:1.2
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-east-1
      AWS_SESSION_TOKEN:
    command:
      - --host=s3.amazonaws.com
    ports:
      - 8080:8080
```
After that, I just ran the `curl -s -H 'host: s3.amazonaws.com' http://localhost:8080/` and it worked flawlessly! Nice!

But, when I try to use it with awscli for example by setting HTTPS_PROXY variable, the following error occurs:

![image](https://user-images.githubusercontent.com/640897/158466994-1eda10ec-68cb-4318-b6fa-256ae3651f9b.png)

Based on PR https://github.com/awslabs/aws-sigv4-proxy/pull/16, I tried to configure name and host as well, but still I got no luck.

Is there a way to make it work using HTTPS_PROXY env var?
